
# SCREEN
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 960
FPS = 60

# COLORS
WHITE = (255, 255, 255)
RED = (255, 0, 0)

# GAME 
GAME_OVER_DELAY = 3200

# PLAYER
PLAYER_WIDTH = 60 
PLAYER_HEIGHT = 70
PLAYER_SPEED = 5

# ENEMY
ENEMY_WIDTH = 46 
ENEMY_HEIGHT = 36
ENEMY_SPAWN_INTERVAL = 2  # Interval for increasing enemy spawns in seconds

# ASTRONAUT
ASTRONAUT_WIDTH = 40 
ASTRONAUT_HEIGHT = 50
ASTRONAUT_SPEED = 3
ASTRONAUT_SPAWN_INTERVAL = 1